
DROP TABLE ARTIST;

CREATE TABLE ARTIST(
ARTIST_ID INT PRIMARY KEY,
NAME VARCHAR(45),
BIRTHPLACE VARCHAR(80),
STYLE_OF_ART VARCHAR(100)
);

DESCRIBE ARTIST;


DROP TABLE ART_WORK;

ALTER TABLE ARTIST ADD ARTIST_ID INT PRIMARY KEY;
ALTER TABLE ARTIST DROP PRIMARY KEY;
DESCRIBE ARTIST;
DESCRIBE ART_WORK;
DESCRIBE CUSTOMER;

DESCRIBE ART_WORK;


CREATE TABLE ART_WORK(
ART_ID INT,
ARTWORK_ID INT PRIMARY KEY,
TITLE VARCHAR(50),
DATE_OF_CREATION DATE,
TYPE VARCHAR(100),
PRICE INT,
FOREIGN KEY (ART_ID) REFERENCES ARTIST(ARTIST_ID)
);

DESCRIBE ART_WORK;

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
ADDRESS VARCHAR(100),
PHONE INT,
PURCHASED_ID INT,
FOREIGN KEY (PURCHASED_ID) REFERENCES ART_WORK(ARTWORK_ID)
);

DESCRIBE CUSTOMER;

INSERT INTO ARTIST (ARTIST_ID, NAME, BIRTHPLACE, STYLE_OF_ART) VALUES (1, 'Leonardo da Vinci', 'Vinci, Italy', 'Renaissance');
INSERT INTO ARTIST (ARTIST_ID, NAME, BIRTHPLACE, STYLE_OF_ART) VALUES (2, 'Vincent van Gogh', 'Zundert, Netherlands', 'Post-Impressionism');
INSERT INTO ARTIST (ARTIST_ID, NAME, BIRTHPLACE, STYLE_OF_ART) VALUES (3, 'Pablo Picasso', 'Málaga, Spain', 'Cubism');

SELECT * FROM ARTIST;

-- Inserting data into the ART_WORK table
INSERT INTO ART_WORK (ART_ID, ARTWORK_ID, TITLE, DATE_OF_CREATION, TYPE, PRICE) 
VALUES (1, 1, 'Mona Lisa', TO_DATE('1503-01-01', 'YYYY-MM-DD'), 'Painting', 100000000);

INSERT INTO ART_WORK (ART_ID, ARTWORK_ID, TITLE, DATE_OF_CREATION, TYPE, PRICE) 
VALUES (2, 2, 'Starry Night', TO_DATE('1889-01-01', 'YYYY-MM-DD'), 'Painting', 80000000);

INSERT INTO ART_WORK (ART_ID, ARTWORK_ID, TITLE, DATE_OF_CREATION, TYPE, PRICE) 
VALUES (3, 3, 'Les Demoiselles d''Avignon', TO_DATE('1907-01-01', 'YYYY-MM-DD'), 'Painting', 120000000);


SELECT * FROM ART_WORK;


INSERT INTO CUSTOMER (ID, NAME, ADDRESS, PHONE, PURCHASED_ID) VALUES (1, 'John Doe', '123 Main St, Anytown', '+1234567890', 1);
INSERT INTO CUSTO9MER (ID, NAME, ADDRESS, PHONE, PURCHASED_ID) VALUES (2, 'Jane Smith', '456 Elm St, Othertown', '+9876543210', 2);
INSERT INTO CUSTOMER (ID, NAME, ADDRESS, PHONE, PURCHASED_ID) VALUES (3, 'Alice Johnson', '789 Oak St, Anothertown', '+1112223333', 3);

DESCRIBE TABLE ARTIST;

SELECT * FROM ARTIST;
SELECT * FROM ART_WORK;
SELECT * FROM CUSTOMER;
DELETE FROM ARTIST;

select table_name from user_tables;

DROP TABLE ARTIST;


SELECT table_name FROM all_tables;


BEGIN
    FOR cur_rec IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/



SELECT * FROM ARTIST WHERE ARTIST_ID = (SELECT ART_ID FROM ART_WORK WHERE ARTWORK_ID = (SELECT ID FROM CUSTOMER WHERE NAME = 'John Doe'));--  (SELECT * FROM CUSTOMER WHERE NAME = 'John Doe');
SELECT * FROM ART_WORK WHERE ARTWORK_ID = (SELECT PURCHASED_ID FROM CUSTOMER WHERE ID = 1);

UPDATE ARTIST SET NAME = 'SOHEL' WHERE ARTIST_ID = (SELECT ART_ID FROM ART_WORK WHERE ARTWORK_ID = (SELECT PURCHASED_ID FROM CUSTOMER WHERE ID = 1));
UPDATE ARTIST SET NAME = 'Leonardo da Vinci' WHERE ARTIST_ID = 1;


INSERT INTO ARTIST (ARTIST_ID, NAME, BIRTHPLACE, STYLE_OF_ART) VALUES (10, 'Leonardo da Vinci', 'KUET', 'Renaissance');
DELETE FROM ARTIST WHERE ARTIST_ID = 10;


SELECT * FROM ARTIST;
SELECT * FROM CUSTOMER;